### ISSUE TITLE
Limits of consults not specified and result in error

### ISSUE THREAD

**Issue by cbethter** [Theryston/gender-name#6]
Error after ~3 hundred requests:
{'statusCode': 500, 'message': 'Internal server error', 'timestamp': '_AAAA-MM-DDT00:MM:SS.MMMZ_', 'path': '/predict?model=gnbr&name=_name_'}
IP locked or banned? I suggest instructing about the limits of requests.

**Comment by Theryston** [comment]
Sorry for the trouble, we were having problems with our servers, but we're back online now. Thanks
